// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaAcademicoG2.Infrastructure.Data;

#nullable disable

namespace SistemaAcademicoG2.Infrastructure.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20251117222332_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SistemaAcademico.Domain.Entities.Inscripcion", b =>
                {
                    b.Property<int>("IdInscripcion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idInscripcion");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdInscripcion"));

                    b.Property<int>("AnioLectivo")
                        .HasColumnType("int")
                        .HasColumnName("anioLectivo");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<DateTime>("FechaIngreso")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("fechaIngreso");

                    b.Property<int>("IdGrado")
                        .HasColumnType("int")
                        .HasColumnName("idGrado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.HasKey("IdInscripcion");

                    b.HasIndex("IdGrado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_Inscripcion", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Asignatura", b =>
                {
                    b.Property<int>("IdAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAsignatura");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsignatura"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdAsignatura");

                    b.ToTable("t_Asignatura", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Asistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdAsistencia");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdAsistencia"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<string>("EstadoAsistencia")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("EstadoAsistencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("Fecha");

                    b.Property<int>("IdDGA")
                        .HasColumnType("int")
                        .HasColumnName("IdDGA");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<string>("Observacion")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Observacion");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("IdDGA");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_Asistencia", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.DocenteAsignaturaGrado", b =>
                {
                    b.Property<int>("IdDGA")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdDGA");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdDGA"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<int?>("GradoAsignaturaIdGradoAsignatura")
                        .HasColumnType("int");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int")
                        .HasColumnName("IdAsignatura");

                    b.Property<int>("IdGrado")
                        .HasColumnType("int")
                        .HasColumnName("IdGrado");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.HasKey("IdDGA");

                    b.HasIndex("GradoAsignaturaIdGradoAsignatura");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdGrado");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_docenteasignaturagrado", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("idGrado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGrado"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("nombre");

                    b.HasKey("IdGrado");

                    b.ToTable("t_Grado", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.GradoAsignatura", b =>
                {
                    b.Property<int>("IdGradoAsignatura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdGradoAsignatura"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int")
                        .HasColumnName("AsignaturaId");

                    b.Property<int>("IdGrado")
                        .HasColumnType("int")
                        .HasColumnName("GradoId");

                    b.HasKey("IdGradoAsignatura");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdGrado");

                    b.ToTable("T_GradoAsignatura");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Nota", b =>
                {
                    b.Property<int>("IdNota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdNota");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdNota"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<string>("EstadoAcademico")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("EstadoAcademico");

                    b.Property<int>("IdAsignatura")
                        .HasColumnType("int")
                        .HasColumnName("IdAsignatura");

                    b.Property<int>("IdPeriodo")
                        .HasColumnType("int")
                        .HasColumnName("IdPeriodo");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    b.Property<decimal>("Nota1")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Nota1");

                    b.Property<decimal>("Nota2")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Nota2");

                    b.Property<decimal>("Nota3")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("Nota3");

                    b.Property<decimal>("PromedioFinal")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("PromedioFinal");

                    b.HasKey("IdNota");

                    b.HasIndex("IdAsignatura");

                    b.HasIndex("IdPeriodo");

                    b.HasIndex("IdUsuario");

                    b.ToTable("t_nota", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Periodo", b =>
                {
                    b.Property<int>("IdPeriodo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdPeriodo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPeriodo"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaFin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("FechaInicio");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdPeriodo");

                    b.ToTable("t_Periodo", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdRol"));

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Nombre");

                    b.HasKey("IdRol");

                    b.ToTable("t_Rol", (string)null);
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdUsuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Apellido");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("Correo");

                    b.Property<bool>("Estado")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("Estado");

                    b.Property<int>("IdRol")
                        .HasColumnType("int")
                        .HasColumnName("IdRol");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Nombre");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("varchar(250)")
                        .HasColumnName("Clave");

                    b.HasKey("IdUsuario");

                    b.HasIndex("IdRol");

                    b.ToTable("t_Usuario", (string)null);
                });

            modelBuilder.Entity("SistemaAcademico.Domain.Entities.Inscripcion", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Grado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Asistencia", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.DocenteAsignaturaGrado", "DocenteAsignaturaGrado")
                        .WithMany("Asistencias")
                        .HasForeignKey("IdDGA")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocenteAsignaturaGrado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.DocenteAsignaturaGrado", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.GradoAsignatura", null)
                        .WithMany("DocentesGradoAsignatura")
                        .HasForeignKey("GradoAsignaturaIdGradoAsignatura");

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("Docentes")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Grado");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.GradoAsignatura", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany()
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Grado", "Grado")
                        .WithMany("GradosAsignaturas")
                        .HasForeignKey("IdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Grado");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Nota", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Asignatura", "Asignatura")
                        .WithMany("Notas")
                        .HasForeignKey("IdAsignatura")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Periodo", "Periodo")
                        .WithMany("Notas")
                        .HasForeignKey("IdPeriodo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Periodo");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("SistemaAcademicoG2.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Asignatura", b =>
                {
                    b.Navigation("Docentes");

                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.DocenteAsignaturaGrado", b =>
                {
                    b.Navigation("Asistencias");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Grado", b =>
                {
                    b.Navigation("GradosAsignaturas");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.GradoAsignatura", b =>
                {
                    b.Navigation("DocentesGradoAsignatura");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Periodo", b =>
                {
                    b.Navigation("Notas");
                });

            modelBuilder.Entity("SistemaAcademicoG2.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
